# SPDX-FileCopyrightText: 2023 Alec Delaney
#
# SPDX-License-Identifier: MIT

name: Windows Install Test CI

on: [pull_request, push]

jobs:
  test-install:
    strategy:
      fail-fast: false
      matrix:
        pyver: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: windows-latest
    steps:
    - name: Set up Python ${{ matrix.pyver }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.pyver }}
    - name: Checkout Current Repo
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Find Python executable
      id: find-pyexec
      run: |
        $pyexecloc = (get-command python).Path
        "pyexec=$pyexecloc" >> $env:GITHUB_OUTPUT
    - name: Install the library
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Install test requirements
      run: |
        pip install -r requirements-test.txt
    - name: Run tests
      run: |
        pytest